---


- hosts: maori-aws
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Create the SSH directory
      file: state=directory path=/home/{{ user }}/.ssh/

    - name: Add local key to authorized_keys template
      authorized_key: user={{ user }}
                      key="{{ lookup('file', 'key.pub') }}"

#    - name: Upload SSH key
#      copy: src=key dest=/home/{{ user }}/.ssh/id_rsa mode=0600