---

- hosts: maori-upload
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: Create the project root directory
      become: yes
      file: state=directory path={{ project_root }} owner={{ user }} group={{ user }} mode=755

    - name: Create user
      become: yes
      user: name={{ user }} state=present

    - name: Create the project directory
      file: state=directory path={{ project_root }}/{{ project_name }} mode=755

    - name: Put config to {{ project_path }}/webapp/conf/config.yml
      template: src=../webapp/conf/config.yml.template dest={{ project_path }}/webapp/conf/config.yml
                owner={{ user }} group={{ user }} mode=0600

    - name: Install required system packages
      become: yes
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Install required Python packages
      become: yes
      pip: name={{ item }} state=latest
      with_items: "{{ python_packages }}"

    - name: Download and install nodejs and npm
      unarchive: src={{ nodejs_url }} dest=/opt/dev copy=no creates=/opt/dev/{{ nodejs_version }}

    - name: Create node and npm symlinks
      become: yes
      file: src=/opt/dev/{{ nodejs_version }}/bin/{{ item }}
            dest=/usr/bin/{{ item }}
            owner={{ user }}
            group={{ user }}
            state=link
      with_items:
        - node
        - npm

    - name: Create config directory for supervisor
      become: yes
      file: path=/etc/supervisor state=directory mode=0700 owner={{ user }} group={{ user }}

    - name: Copy supervisor config file
      copy: src=supervisord.conf dest=/etc/supervisor/supervisord.conf mode=0600 owner={{ user }} group={{ user }}

    - name: Copy maori-upload supervisor config file
      template: src=maori-upload.supervisor.j2 dest=/etc/supervisor/maori-upload.supervisor mode=0600 owner={{ user }} group={{ user }}

    - name: Enable ip traffic forwarding
      become: yes
      sysctl: name="net.ipv4.conf.eth0.forwarding" value=1 sysctl_set=yes

    - name: Forward traffic from 80 to 9777 port
      become: yes
      iptables: table=nat chain=PREROUTING in_interface=eth0 protocol=tcp match=tcp destination_port=80 jump=REDIRECT to_ports=9777 comment="Redirect web traffic to port 9777"

    - name: Persist iptables rules
      become: yes
      command: sh -c "iptables-save > /etc/iptables.rules"

    - name: Put iptablesload script to /etc/network/if-pre-up.d
      become: yes
      copy: src=iptablesload dest=/etc/network/if-pre-up.d/iptablesload mode=0755

#    - name: Start supervisord daemon
#      shell: supervisord -c /etc/supervisor/supervisord.conf -l {{ project_path}}/supervisord.log

#    - name: Mount code folder
#      mount: fstype=vboxsf opts=uid={{ project_name }},gid={{ project_name }} name={{ project_root }}/code/ src={{ project_name }} state=mounted
#      only_if: "$vm == 1"
