# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 22, host: 2223, id: 'ssh'
  config.vm.network "forwarded_port", guest: 9777, host: 9777

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  #config.ssh.insert_key = false
  #config.ssh.username = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'maori-upload'
    vb.memory = 2048
	vb.cpus = 2
  end

  #config.vm.provision :ansible do |ansible|
  #  ansible.verbose = "vvv"
  #  ansible.inventory_path = "hosts"
  #  ansible.playbook = "vbox-setup.yml"
  #  ansible.host_key_checking = false
  #end
end
